<Project>
	<!-- Settings shared by the projects which compile nuget packages -->
	<PropertyGroup>
		<Nullable>enable</Nullable>
		<CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>ConstMe</Authors>
		<Company>Vrmac Softver</Company>
		<Version>1.0</Version>
		<PackageReadmeFile>Readme.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="Readme.md" Pack="true" PackagePath="\" />
		<Compile Include="../AssemblyInfoShared.cs" Link="AssemblyInfoShared.cs" />
	</ItemGroup>
</Project>