<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../Vrmac.props" />
	<PropertyGroup>
		<PackageProjectUrl>https://github.com/Const-me/Vrmac.Web/tree/master/Vrmac.Uploads</PackageProjectUrl>
	</PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Vrmac.Utils\Vrmac.Utils.csproj" />
	</ItemGroup>
</Project>