<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../Vrmac.props" />
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="System.IO.Hashing" Version="10.0.12" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Vrmac.Utils\Vrmac.Utils.csproj" />
	</ItemGroup>
</Project>