namespace Vrmac;

/// <summary>Converts the DOM parsed by <see cref="SourceParser"/> into C# source code</summary>
static class Generator
{
	static IEnumerable<Element> flatten( this IEnumerable<Element> sequence )
	{
		foreach( Element e in sequence )
		{
			yield return e;

			if( e is Block block )
			{
				foreach( Element e2 in block.children.flatten() )
					yield return e2;
			}
		}
	}

	static HashSet<string> collectPlaceholders( IReadOnlyList<Element> list )
	{
		HashSet<string> names = new();
		foreach( Placeholder e in list.flatten().OfType<Placeholder>() )
			names.Add( e.name );
		return names;
	}

	static HashSet<string> collectBlocks( IReadOnlyList<Element> list )
	{
		HashSet<string> names = new();
		foreach( Block e in list.flatten().OfType<Block>() )
			names.Add( e.name );
		return names;
	}

	static Dictionary<Element, string> collectTextSpans( IReadOnlyList<Element> list )
	{
		Dictionary<Element, string> dict = new();
		Dictionary<string, string> content = new();
		foreach( Text elt in list.flatten().OfType<Text>() )
		{
			string text = elt.text;
			if( content.TryGetValue( text, out string name ) )
			{
				dict.Add( elt, name );
				continue;
			}

			int usn = content.Count;
			name = $"s_text{usn}";
			dict.Add( elt, name );
			content.Add( text, name );
		}
		return dict;
	}

	static readonly Dictionary<char, string> escapes = new()
	{
		{'"', "\\\"" },
		{'\n', "\\n" },
		{'\r', "\\r" },
		{'\t', "\\t" },
	};

	static void writeTextSpans( StreamWriter w, Dictionary<Element, string> dict )
	{
		if( dict.Count <= 0 )
			return;
		w.WriteLine();

		HashSet<string> written = new();
		foreach( var kvp in dict )
		{
			if( !written.Add( kvp.Value ) )
				continue;

			w.WriteLine( "\tstatic ReadOnlySpan<byte> {0} =>", kvp.Value );
			w.Write( "\t\t\"" );
			string source = ( (Text)kvp.Key ).text;
			foreach( char c in source )
			{
				if( escapes.TryGetValue( c, out string? es ) )
					w.Write( es );
				else
					w.Write( c );
			}
			w.WriteLine( "\"u8;" );
		}
	}

	/// <summary>Convert the DOM parsed by <see cref="SourceParser"/> into C# source code</summary>
	public static void generateSource( StreamWriter w, string name, string ns, string template,
		IReadOnlyList<Element> list, string? route, bool routeCached )
	{
		bool hasRoute = !string.IsNullOrWhiteSpace( route );
		if( hasRoute )
			w.WriteLine( "#nullable enable" );
		w.WriteLine( "// This source file is generated by a tool" );
		if( hasRoute && ns != "Vrmac.Html" )
			w.WriteLine( "using Vrmac.Html;" );
		if( !string.IsNullOrWhiteSpace( ns ) )
			w.WriteLine( "namespace {0};", ns );
		w.WriteLine();

		HashSet<string> placeholders = collectPlaceholders( list );
		HashSet<string> blocks = collectBlocks( list );
		bool anyPlaceholders = placeholders.Count > 0 || blocks.Count > 0;
		if( anyPlaceholders )
		{
			w.WriteLine( "/// <summary>Source data for the <c>{0}</c> template</summary>", template );
			w.WriteLine( "interface i{0}", name );
			w.WriteLine( "{" );
			foreach( string id in placeholders )
			{
				w.WriteLine( "\t/// <summary>Write content of the <c>@{0}</c> placeholder</summary>", id );
				w.WriteLine( "\tvoid {0}( Stream stream );", id );
			}
			foreach( string id in blocks )
			{
				w.WriteLine( "\t/// <summary>Return false to skip the <c>{0}</c> conditional block of the template</summary>", id );
				w.WriteLine( "\tbool {0}();", id );
			}
			w.WriteLine( "}" );
			w.WriteLine();
		}

		if( hasRoute )
		{
			string baseIface = routeCached ? "iStaticPage" : "iDynamicPage";
			w.WriteLine( "/// <summary>Partial structure implementing the <c>{0}</c> {1} web page</summary>",
				template, routeCached ? "cached" : "dynamic" );
			w.WriteLine( "partial struct {0}: {1}", name, baseIface );
			w.WriteLine( "{" );

			w.WriteLine( "\t/// <summary>The route pattern</summary>" );
			w.WriteLine( "\tinternal const string routePattern = \"{0}\";", route );
			w.WriteLine();

			if( !routeCached )
			{
				w.WriteLine( "\t/// <summary>Handler for GET method</summary>" );
				w.WriteLine( "\tstatic Task renderPage( HttpContext context, object? state = null ) => DynamicPage.render<{0}>( context, state );", name );
				w.WriteLine( "\t/// <summary>Handler for GET method</summary>" );
				w.WriteLine( "\tstatic Task renderSecure( HttpContext context, object? state = null ) => DynamicPage.renderSecure<{0}>( context, state );", name );
			}
			else
			{
				w.WriteLine( "\t/// <summary>Render cached response</summary>" );
				w.WriteLine( "\tstatic CachedResponse renderPage( DateTime modified, object? state = null ) => CachedPage.render<{0}>( modified, state );", name );
			}
			w.WriteLine();
		}
		else
		{
			w.WriteLine( "/// <summary>Partial class to render the <c>{0}</c> template</summary>", template );
			w.WriteLine( "static partial class {0}", name );
			w.WriteLine( "{" );
		}

		Dictionary<Element, string> spans = collectTextSpans( list );

		w.WriteLine( "\t/// <summary>Write HTML into the stream of UTF-8 bytes</summary>" );
		w.Write( "\t" );
		if( !hasRoute )
			w.Write( "public " );
		if( anyPlaceholders )
			w.WriteLine( "static void applyTemplate<T>( Stream response, in T model ) where T: i{0}, allows ref struct", name );
		else
			w.WriteLine( "static void applyTemplate( Stream response )" );
		w.WriteLine( "\t{" );
		writeApply( w, list, spans, 2 );
		w.WriteLine( "\t}" );
		writeTextSpans( w, spans );
		w.Write( "}" );
		w.Flush();
	}

	static void writeApply( StreamWriter w, IReadOnlyList<Element> list, Dictionary<Element, string> spans, int indentLevel )
	{
		string indent = new string( '\t', indentLevel );
		foreach( Element elt in list )
		{
			if( elt is Text )
			{
				w.WriteLine( "{0}response.Write( {1} );", indent, spans[ elt ] );
				continue;
			}
			if( elt is Placeholder p )
			{
				w.WriteLine( "{0}model.{1}( response );", indent, p.name );
				continue;
			}
			if( elt is Block block )
			{
				w.WriteLine( "{0}if( model.{1}() )", indent, block.name );
				w.WriteLine( "{0}{{", indent );
				writeApply( w, block.children, spans, indentLevel + 1 );
				w.WriteLine( "{0}}}", indent );
				continue;
			}
			throw new NotImplementedException();
		}
	}
}