<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../Vrmac.props" />

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<PublishAot>true</PublishAot>
		<InvariantGlobalization>true</InvariantGlobalization>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<IlcInstructionSet>avx2,vectort128</IlcInstructionSet>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<PublishTrimmed>true</PublishTrimmed>
		<PublishSingleFile>true</PublishSingleFile>
		<PublishAot>true</PublishAot>
		<SelfContained>true</SelfContained>
		<TrimMode>Full</TrimMode>
		<StripSymbols>true</StripSymbols>
		<DebuggerSupport>false</DebuggerSupport>
		<IlcTrimMetadata>true</IlcTrimMetadata>
		<EnableDiagnostics>false</EnableDiagnostics>
		<StackTraceSupport>false</StackTraceSupport>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Transform\regionFromCountry.gz" />
		<EmbeddedResource Include="Transform\regionFromCountry.gz" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Vrmac.GeoIP\Vrmac.GeoIP.csproj" />
	</ItemGroup>

</Project>