<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../Vrmac.props" />
	<PropertyGroup>
		<PackageProjectUrl>https://github.com/Const-me/Vrmac.Web/tree/master/Vrmac.Markdown</PackageProjectUrl>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Vrmac.Utils\Vrmac.Utils.csproj" />
		<PackageReference Include="Markdig.Signed" Version="1.4.0" />
	</ItemGroup>

</Project>