<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../Vrmac.props" />
	<PropertyGroup>
		<PackageProjectUrl>https://github.com/Const-me/Vrmac.Web/tree/master/Vrmac.Acme</PackageProjectUrl>
		<Description>A client for ACME v2 protocol</Description>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.0" />
	</ItemGroup>
</Project>